apiVersion: v1
kind: Service
metadata:
  name: service-nodeport-{{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30000
  selector:
    app: poc-security-example-api